# Generated by Django 3.2.3 on 2021-06-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0004_participante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participante',
            old_name='nombe',
            new_name='nombre',
        ),
    ]
